data:
  data_dir: data/geolife_eps20/processed
  dataset: geolife
  dataset_prefix: geolife_eps20_prev7
  experiment_root: experiments/ht_optuna_20251231_152825_4f151c10
dataset_info:
  total_loc_num: 1187
  total_user_num: 46
embedding:
  base_emb_size: 128
  poi_original_size: 16
model:
  dim_feedforward: 128
  fc_dropout: 0.2
  networkName: transformer
  nhead: 2
  num_encoder_layers: 8
optimiser:
  beta1: 0.9
  beta2: 0.999
  lr: 0.0005
  lr_gamma: 0.1
  lr_step_size: 1
  max_epoch: 50
  momentum: 0.98
  num_training_epochs: 50
  num_warmup_epochs: 2
  optimizer: Adam
  patience: 5
  weight_decay: 1.0e-06
seed: 42
training:
  batch_size: 32
  day_selection: default
  debug: false
  if_embed_duration: true
  if_embed_poi: false
  if_embed_time: true
  if_embed_user: true
  num_workers: 0
  previous_day: 7
  print_step: 20
  verbose: true
