data:
  data_dir: data/diy_eps50/processed
  dataset: diy
  dataset_prefix: diy_eps50_prev7
  experiment_root: experiments/ht_optuna_20251231_104150_c770bedd
dataset_info:
  total_loc_num: 7038
  total_user_num: 693
embedding:
  base_emb_size: 32
  poi_original_size: 16
model:
  dim_feedforward: 512
  fc_dropout: 0.1
  networkName: transformer
  nhead: 4
  num_encoder_layers: 2
optimiser:
  beta1: 0.9
  beta2: 0.999
  lr: 0.001
  lr_gamma: 0.1
  lr_step_size: 1
  max_epoch: 50
  momentum: 0.98
  num_training_epochs: 50
  num_warmup_epochs: 2
  optimizer: Adam
  patience: 5
  weight_decay: 1.0e-06
seed: 42
training:
  batch_size: 256
  day_selection: default
  debug: false
  if_embed_duration: true
  if_embed_poi: false
  if_embed_time: true
  if_embed_user: true
  num_workers: 0
  previous_day: 7
  print_step: 10
  verbose: true
