data:
  data_dir: data/diy_eps50/processed
  dataset: diy
  dataset_prefix: diy_eps50_prev14
  experiment_root: experiments/ht_optuna_20260101_081958_05571f15
dataset_info:
  total_loc_num: 4866
  total_user_num: 285
embedding:
  base_emb_size: 32
  poi_original_size: 16
model:
  fc_dropout: 0.1
  lstm_dropout: 0.2
  lstm_hidden_size: 64
  lstm_num_layers: 2
  networkName: lstm
optimiser:
  beta1: 0.9
  beta2: 0.999
  lr: 0.001
  lr_gamma: 0.1
  lr_step_size: 1
  max_epoch: 50
  momentum: 0.98
  num_training_epochs: 50
  num_warmup_epochs: 2
  optimizer: Adam
  patience: 5
  weight_decay: 1.0e-06
seed: 42
training:
  batch_size: 256
  day_selection: default
  debug: false
  if_embed_duration: true
  if_embed_poi: false
  if_embed_time: true
  if_embed_user: true
  num_workers: 0
  previous_day: 14
  print_step: 10
  verbose: true
